---
- name: Wait for bootstrap to complete
  command:
    cmd: openshift-install wait-for bootstrap-complete
    chdir: "{{ openshift_install_dir }}"

- name: Remove bootstrap node
  terraform:
    project_path: "{{ openshift_terraform_dir }}"
    state: absent
    targets: ['module.bootstraps']
    variables:
      fqdn: "{{ openshift_fqdn }}"
      master_image: "{{ openshift_master_osimage }}"
      worker_image: "{{ openshift_worker_osimage }}"
      bootstrap_image: "{{ openshift_bootstrap_osimage }}"
      loadbalancer_image: "{{ openshift_loadbalancer_osimage }}"


# todo: only check these if worker nodes don't have CSRs?
# todo: this is flaky - make it better
- name: Approve worker node bootstrapper CSRs
  include_tasks: util/approve_csrs.yml
  vars:
    expected_csr_count: "{{ openshift_hosts.workers | length }}"

- name: Approve worker CSRs
  include_tasks: util/approve_csrs.yml
  vars:
    expected_csr_count: "{{ openshift_hosts.workers | length }}"

- name: Wait for installation to complete
  command:
    cmd: openshift-install wait-for install-complete
    chdir: "{{ openshift_install_dir }}"
